apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-devsecops-deployment
  namespace: cloud-native-devsecops
  labels:
    app: cloud-native-devsecops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-native-devsecops

  template:
    metadata:
      labels:
        app: cloud-native-devsecops

    spec:
      containers:
      - name: cloud-native-devsecops-container

        image: 781863585859.dkr.ecr.us-east-1.amazonaws.com/cloud-native-devsecops-eks:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5