apiVersion: v1
kind: Service

metadata:
  name: cloud-native-devsecops-service
  namespace: cloud-native-devsecops

spec:
  selector:
    app: cloud-native-devsecops

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: LoadBalancer